# TCL File Generated by Component Editor 18.1
# Wed Apr 15 12:39:35 ICT 2026
# DO NOT MODIFY


# 
# mlp_accelerator "MLP Accelerator (MNIST TinyML)" v1.0
# Custom 2026.04.15.12:39:35
# TinyML MLP Accelerator for MNIST Digit Recognition (784->128->10)
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module mlp_accelerator
# 
set_module_property DESCRIPTION "TinyML MLP Accelerator for MNIST Digit Recognition (784->128->10)"
set_module_property NAME mlp_accelerator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Custom IP/TinyML"
set_module_property AUTHOR Custom
set_module_property DISPLAY_NAME "MLP Accelerator (MNIST TinyML)"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mlp_accelerator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file mlp_accelerator.v VERILOG PATH mlp_accelerator.v TOP_LEVEL_FILE
add_fileset_file mac_unit.v VERILOG PATH mac_unit.v
add_fileset_file weight_rom.v VERILOG PATH weight_rom.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL mlp_accelerator
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file mlp_accelerator.v VERILOG PATH mlp_accelerator.v
add_fileset_file mac_unit.v VERILOG PATH mac_unit.v
add_fileset_file weight_rom.v VERILOG PATH weight_rom.v


# 
# parameters
# 
add_parameter INPUT_SIZE INTEGER 784
set_parameter_property INPUT_SIZE DEFAULT_VALUE 784
set_parameter_property INPUT_SIZE DISPLAY_NAME INPUT_SIZE
set_parameter_property INPUT_SIZE TYPE INTEGER
set_parameter_property INPUT_SIZE UNITS None
set_parameter_property INPUT_SIZE HDL_PARAMETER true
add_parameter HIDDEN_SIZE INTEGER 128
set_parameter_property HIDDEN_SIZE DEFAULT_VALUE 128
set_parameter_property HIDDEN_SIZE DISPLAY_NAME HIDDEN_SIZE
set_parameter_property HIDDEN_SIZE TYPE INTEGER
set_parameter_property HIDDEN_SIZE UNITS None
set_parameter_property HIDDEN_SIZE HDL_PARAMETER true
add_parameter OUTPUT_SIZE INTEGER 10
set_parameter_property OUTPUT_SIZE DEFAULT_VALUE 10
set_parameter_property OUTPUT_SIZE DISPLAY_NAME OUTPUT_SIZE
set_parameter_property OUTPUT_SIZE TYPE INTEGER
set_parameter_property OUTPUT_SIZE UNITS None
set_parameter_property OUTPUT_SIZE HDL_PARAMETER true
add_parameter W1_DEPTH INTEGER 100352
set_parameter_property W1_DEPTH DEFAULT_VALUE 100352
set_parameter_property W1_DEPTH DISPLAY_NAME W1_DEPTH
set_parameter_property W1_DEPTH TYPE INTEGER
set_parameter_property W1_DEPTH UNITS None
set_parameter_property W1_DEPTH HDL_PARAMETER true
add_parameter W2_DEPTH INTEGER 1280
set_parameter_property W2_DEPTH DEFAULT_VALUE 1280
set_parameter_property W2_DEPTH DISPLAY_NAME W2_DEPTH
set_parameter_property W2_DEPTH TYPE INTEGER
set_parameter_property W2_DEPTH UNITS None
set_parameter_property W2_DEPTH HDL_PARAMETER true
add_parameter L1_REQUANT_MULT INTEGER 12 "Requantization multiplier (from Python training)"
set_parameter_property L1_REQUANT_MULT DEFAULT_VALUE 12
set_parameter_property L1_REQUANT_MULT DISPLAY_NAME "Layer 1 Requant Multiplier"
set_parameter_property L1_REQUANT_MULT TYPE INTEGER
set_parameter_property L1_REQUANT_MULT UNITS None
set_parameter_property L1_REQUANT_MULT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property L1_REQUANT_MULT DESCRIPTION "Requantization multiplier (from Python training)"
set_parameter_property L1_REQUANT_MULT HDL_PARAMETER true
add_parameter L1_REQUANT_SHIFT INTEGER 15 "Requantization right-shift bits"
set_parameter_property L1_REQUANT_SHIFT DEFAULT_VALUE 15
set_parameter_property L1_REQUANT_SHIFT DISPLAY_NAME "Layer 1 Requant Shift"
set_parameter_property L1_REQUANT_SHIFT TYPE INTEGER
set_parameter_property L1_REQUANT_SHIFT UNITS None
set_parameter_property L1_REQUANT_SHIFT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property L1_REQUANT_SHIFT DESCRIPTION "Requantization right-shift bits"
set_parameter_property L1_REQUANT_SHIFT HDL_PARAMETER true
add_parameter LEAKY_SHIFT INTEGER 3 "Leaky ReLU alpha = 1/2^N (default: N=3, alpha=0.125)"
set_parameter_property LEAKY_SHIFT DEFAULT_VALUE 3
set_parameter_property LEAKY_SHIFT DISPLAY_NAME "Leaky ReLU Shift"
set_parameter_property LEAKY_SHIFT TYPE INTEGER
set_parameter_property LEAKY_SHIFT UNITS None
set_parameter_property LEAKY_SHIFT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LEAKY_SHIFT DESCRIPTION "Leaky ReLU alpha = 1/2^N (default: N=3, alpha=0.125)"
set_parameter_property LEAKY_SHIFT HDL_PARAMETER true
add_parameter W1_INIT_FILE STRING w1_int8.hex "Hidden layer weights (784x128, INT8)"
set_parameter_property W1_INIT_FILE DEFAULT_VALUE w1_int8.hex
set_parameter_property W1_INIT_FILE DISPLAY_NAME "W1 Weight File"
set_parameter_property W1_INIT_FILE TYPE STRING
set_parameter_property W1_INIT_FILE UNITS None
set_parameter_property W1_INIT_FILE DESCRIPTION "Hidden layer weights (784x128, INT8)"
set_parameter_property W1_INIT_FILE HDL_PARAMETER true
add_parameter W2_INIT_FILE STRING w2_int8.hex "Output layer weights (128x10, INT8)"
set_parameter_property W2_INIT_FILE DEFAULT_VALUE w2_int8.hex
set_parameter_property W2_INIT_FILE DISPLAY_NAME "W2 Weight File"
set_parameter_property W2_INIT_FILE TYPE STRING
set_parameter_property W2_INIT_FILE UNITS None
set_parameter_property W2_INIT_FILE DESCRIPTION "Output layer weights (128x10, INT8)"
set_parameter_property W2_INIT_FILE HDL_PARAMETER true
add_parameter B1_INIT_FILE STRING b1_int32.hex "Hidden layer bias (128, INT32)"
set_parameter_property B1_INIT_FILE DEFAULT_VALUE b1_int32.hex
set_parameter_property B1_INIT_FILE DISPLAY_NAME "Bias File"
set_parameter_property B1_INIT_FILE TYPE STRING
set_parameter_property B1_INIT_FILE UNITS None
set_parameter_property B1_INIT_FILE DESCRIPTION "Hidden layer bias (128, INT32)"
set_parameter_property B1_INIT_FILE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 1
set_interface_property avalon_slave readWaitStates 0
set_interface_property avalon_slave readWaitTime 0
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avs_address address Input 11
add_interface_port avalon_slave avs_read read Input 1
add_interface_port avalon_slave avs_write write Input 1
add_interface_port avalon_slave avs_writedata writedata Input 32
add_interface_port avalon_slave avs_readdata readdata Output 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point result_digit_conduit
# 
add_interface result_digit_conduit conduit end
set_interface_property result_digit_conduit associatedClock clock
set_interface_property result_digit_conduit associatedReset reset
set_interface_property result_digit_conduit ENABLED true
set_interface_property result_digit_conduit EXPORT_OF ""
set_interface_property result_digit_conduit PORT_NAME_MAP ""
set_interface_property result_digit_conduit CMSIS_SVD_VARIABLES ""
set_interface_property result_digit_conduit SVD_ADDRESS_GROUP ""

add_interface_port result_digit_conduit result_digit result_digit Output 4


# 
# connection point result_valid_conduit
# 
add_interface result_valid_conduit conduit end
set_interface_property result_valid_conduit associatedClock clock
set_interface_property result_valid_conduit associatedReset reset
set_interface_property result_valid_conduit ENABLED true
set_interface_property result_valid_conduit EXPORT_OF ""
set_interface_property result_valid_conduit PORT_NAME_MAP ""
set_interface_property result_valid_conduit CMSIS_SVD_VARIABLES ""
set_interface_property result_valid_conduit SVD_ADDRESS_GROUP ""

add_interface_port result_valid_conduit result_valid result_valid Output 1


# 
# connection point irq_sender
# 
add_interface irq_sender interrupt end
set_interface_property irq_sender associatedAddressablePoint avalon_slave
set_interface_property irq_sender associatedClock clock
set_interface_property irq_sender associatedReset reset
set_interface_property irq_sender bridgedReceiverOffset ""
set_interface_property irq_sender bridgesToReceiver ""
set_interface_property irq_sender ENABLED true
set_interface_property irq_sender EXPORT_OF ""
set_interface_property irq_sender PORT_NAME_MAP ""
set_interface_property irq_sender CMSIS_SVD_VARIABLES ""
set_interface_property irq_sender SVD_ADDRESS_GROUP ""

add_interface_port irq_sender irq irq Output 1

